// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
= Open Liberty Cheat Sheet
Andy Guibert <https://twitter.com/andrew_guibert[@andrew_guibert]>

:toc: left
:source-highlighter: highlightjs
:sectnums:

== What is Open Liberty?

https://openliberty.io/[OpenLiberty] is a lightweight open framework for building fast and efficient cloud-native Java microservices. It supports some of the most popular Java standards today, including:

- Java EE 7 and 8
- Microprofile 1.X, 2.X, and 3.X
- Spring Boot 1.5 and 2.0

== TL;DR info

- Get OpenLiberty using Maven/Gradle/Docker here: https://openliberty.io/downloads/
- Create server: `<liberty-root>/bin/server create myServer`
- Start server: `<liberty-root>/bin/server start myServer`
- Main config file: `<liberty-root>/usr/servers/myServer/server.xml`
- Default app folder: `<liberty-root>/usr/servers/myServer/dropins/` 
- Default ports: http=9080, https=9443
- Enable only the features you need for smaller disk/memory footprint and faster start time
- Develop apps using "dev mode" using the Liberty Maven Plugin `mvn liberty:dev` goal
- Lots of useful guides here: https://openliberty.io/guides/

== Getting Started

Generate a basic Liberty project using the https://start.microprofile.io/[MicroProfile Starter] website:

1. Select "MicroProfile 3.0" for MicroProfile version
2. Select "OpenLiberty" for MicroProfile Runtime
3. Select any example specifications you want to be included
4. Download and extract the project, then import into your preferred IDE


This creates a Maven project with a simple JAX-RS resource class in it:

[source,java]
----
@Path("/hello")
@Singleton
public class HelloController {

    @GET
    public String sayHello() {
        return "Hello World";
    }
}
----

You can start the application in "dev mode" using the command:

[source,shell]
----
mvn liberty:dev
----

Then open a web browser to http://localhost:8181/data/hello to access the JAX-RS endpoint. You will see the text `Hello World`.

If you make code changes the application will automatically be updated.

If you add tests to the project, you can run them from dev mode by pressing the `Enter` key. To exit dev mode press `Ctrl+C`.

A more detailed Getting Started walkthrough can be found in the https://openliberty.io/guides/maven-intro.html[OpenLiberty Maven guide].

== Configuration

The primary source of configuration for a Liberty server is the `server.xml` file. In most projects it is located at `src/main/liberty/config/server.xml` and might look like this:

[source,xml]
----
<server>
    <featureManager>
        <feature>servlet-4.0</feature>
    </featureManager>
    
    <httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443"/>
    
    <webApplication location="test.war" name="test"/>
</server>
----

For more info see: https://openliberty.io/docs/ref/feature/[OpenLiberty server configuration overview]

=== Dynamic Configuration

All configuration in `server.xml` is dynamic by default, meaning that if you modify it while the server is running, the server will automatically update to account for the change -- typically in a few milliseconds.

=== Variable Substitution

Server configuration can be parameterized using variables. When resolving variable names the following sources are consulted in increasing order of precedence:

- server.xml default variable values
- environment variables
- bootstrap.properties
- Java system properties (i.e. jvm.options)
- server.xml config

Variables are referenced using `${variableName}` syntax. In server config, specify variables using the variable element:

[source,xml]
----
<variable name="variableName" value="some.value" />
----

Default values, specified in server config, are only used if no other value can be found. They are specified using the variable element and the `defaultValue` attribute:

[source,xml]
----
<variable name="DB_SERVER" defaultValue="localhost"/>
----

=== Predefined Variables

- `${wlp.install.dir}` - the location where the Liberty runtime is installed.
- `${wlp.server.name}` - the name of the server.
- `${wlp.user.dir}` - the location of the usr folder. Defaults to ${wlp.install.dir}/usr.
- `${shared.app.dir}` - the location of shared applications. Defaults to ${wlp.user.dir}/shared/apps.
- `${shared.config.dir}` - the directory that contains the server config. Defaults to ${wlp.user.dir}/shared/config.
- `${shared.resource.dir}` - the location of shared resource files. Defaults to ${wlp.user.dir}/shared/resources.
- `${server.config.dir}` - the directory that server config is stored in. Defaults to ${wlp.user.dir}/servers/${wlp.server.name}.
- `${server.output.dir}` - the directory that the server writes the workarea, logs and other runtime generated files to. Defaults to ${server.config.dir}.


=== Configuration Secrets

If you are running your application in Kubernetes, you don't want to have credentials exposed as simple environment variables, and you certainly don't want them checked in with the rest of your application source code!

First, configure a Kubernetes secret, for example `database-credentials` with the contents:

[source,properties]
----
my-app.db.username=dbUser
my-app.db.password=dbPass
----

Then, you can inject the Kubernetes secret contents into a a `boostrap.properties` file that contains sensitive information as follows:

[source,yaml]
----
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: my-app
spec:
# ...
      containers:
      - name: my-app
        image: ...
        volumeMounts:
        - name: database-credentials-volume
          mountPath: /opt/wlp/usr/servers/defaultServer/bootstrap.properties
          subPath: bootstrap.properties
          readOnly: true
      volumes:
      - name: database-credentials-volume
        secret:
          secretName: database-credentials
----

Finally, the secrets can then be referenced in server configuration using variables:

[source,xml]
----
  <dataSource ...>
    <properties ...
        user="${my-app.db.username}"
        password="${my-app.db.password}"/>
  </dataSource>
----

== Features

The features enabled for a Liberty server are listed in the `<featureManager>` element. A Liberty feature may include other Liberty features. For example, the `jsp-2.3` feature pulls in the `servlet-4.0` feature, and the `webProfile-8.0` feature pulls in all of the features for Java EE 8 Web Profile.

TIP: Only enable the features that you need! While it may be convenient to enable "convenience" features like `javaee-8.0` initially, over time you should only enable features that your application actually needs. Less features = faster startup and lower disk/memory footprint

Some of the most common Liberty features are:

=== Java EE 8
- `webProfile-8.0`: Enables all features in Java EE 8 Web profile: Bean Validation 2.0, CDI 2.0, EJB Lite 3.2, EL 3.0, JAX-RS 2.1, JNDI 1.0, JPA 2.2, JSF 2.3, JSON-B 1.0, JSON-P 1.1, JSP 2.3, Servlet 4.0, WebSocket 1.1
- `javaee-8.0`: Enables all features in Java EE 8 Full Profile: `webProfile-8.0` plus Java Batch 1.0, EE Concurrency 1.0, EJB 3.2, JavaMail 1.6, JAX-WS 2.2, JCA 1.7, JMS 2.0
- `jaxrs-2.1`: Java XML RESTful Web Services (JAX-RS) 2.1
- `cdi-2.0`: Context Dependency Injection (CDI) 2.0
- `jpa-2.2`: Java Persistence Architecture (JPA) 2.2
- `jsf-2.3`: Java Server Faces (JSF) 2.3
- `jsonb-1.0`: JSON Binding (JSON-B) 1.0
- `servlet-4.0`: Servlet 4.0

=== Java EE 7
- `webProfile-7.0`: Enables all features in Java EE 7 Web Profile
- `javaee-7.0`: Enables all features in Java EE 7 Full Profile

WARNING: You cannot mix Java EE 7 and 8 features in the same server.xml!

=== MicroProfile 3.3
- `microProfile-3.3`: Enables all features in MicroProfile 3.3 platform
- `cdi-2.0`
- `jaxrs-2.1`
- `jsonb-1.0`
- `mpConfig-1.4`: MicroProfile Config 1.4
- `mpHealth-2.1`: MicroProfile Health 2.1
- `mpMetrics-2.2`: MicroProfile Metrics 2.2
- `mpRestClient-1.3`: MicroProfile REST Client 1.3

A complete list of all Liberty features can be found here: https://openliberty.io/docs/ref/feature/[OpenLiberty Server Features]

== Maven

Add the maven plugin to your pom.xml file:

[source,xml]
----
<plugin>
    <groupId>io.openliberty.tools</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <version>3.1</version>
</plugin>
----

Some of the essential maven commands are:

- `mvn liberty:dev`: Starts your Liberty server in "dev mode" which runs the application and automatically updates it whenever you save changes to the source code or configuration
- `mvn liberty:run`: Starts your Liberty server in the foreground. Stop it with `Ctrl+C`
- `mvn liberty:start`: Starts your Liberty server in the background
- `mvn liberty:stop`: Stops your Liberty server that was started using `liberty:start`

Also see:

- https://github.com/OpenLiberty/ci.maven[Liberty Maven Plugin source code and documentation]
- https://openliberty.io/guides/maven-intro.html[OpenLiberty Maven guide]

== Gradle

Add the following snippet to your build.gradle file:

[source,javascript]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.7'
    }
}

apply plugin: 'war'
apply plugin: 'liberty'

dependencies {
    libertyRuntime group:'io.openliberty', name:'openliberty-runtime', version:'19.0.0.12'
}
----

Some of the essential gradle tasks are:

- `./gradlew libertyRun`: Starts your Liberty server in the foreground. Stop it with `Ctrl+C`
- `./gradlew libertyStart`: Starts your Liberty server in the background
- `./gradlew libertyStop`: Stops your Liberty server that was started using `liberty:start`

Also see:

- https://github.com/OpenLiberty/ci.gradle[Liberty Gradle Plugin source code and documentation]
- https://openliberty.io/guides/gradle-intro.html[OpenLiberty Gradle guide]

== Docker

The basic Liberty Dockerfile looks like this:

[source,dockerfile]
----
FROM openliberty/open-liberty:full-java8-openj9-ubi
COPY src/main/liberty/config /config/
ADD target/myApp.war /config/dropins

# Running configure.sh takes ~20s at docker build time but will greatly reduce
# container start time. You may not want to run this for local development if
# you are constantly changing the app layer, but should used for production
RUN configure.sh
----

There are also base layers using Java 11 and 13 which can be found here: https://hub.docker.com/r/openliberty/open-liberty[OpenLiberty Docker Hub]

== Supported Java SE versions

OpenLiberty is currently supported on Java SE 8, 11, and 13. Official documentation can be found here: https://openliberty.io/docs/ref/general/#java-se.html[JavaSE support]

== Databases

This is the most common base configuration for using a JDBC DataSource (or JPA) with Liberty:

[source,xml]
----
<featureManager>
    <feature>jdbc-4.2</feature>
</featureManager>
  
<library id="driver-library">
    <fileset dir="/path/to/driver/dir" includes="*.jar"/>
</library>
----

=== PostgreSQL

[source,xml]
----
<dataSource id="DefaultDataSource" jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="driver-library"/>
    <properties.postgresql serverName="localhost" portNumber="5432"
                databaseName="myDB"
                user="exampleUser"
                password="examplePassword"/>

</dataSource>
----

To run a Postgres Docker container locally:

[source,shell]
----
docker run -it --rm=true --memory-swappiness=0 --ulimit memlock=-1:-1 \
           --name postgres-liberty \
           -e POSTGRES_USER=exampleUser \
           -e POSTGRES_PASSWORD=examplePassword \
           -e POSTGRES_DB=myDB \
           -p 5432:5432 postgres:10.5
----

=== IBM DB2

[source,xml]
----
<dataSource id="DefaultDataSource" jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="driver-library"/>
    <properties.db2.jcc serverName="localhost" portNumber="50000"
                databaseName="myDB"
                user="exampleUser"
                password="examplePassword"/>

</dataSource>
----

To run a DB2 Docker container locally:

[source,shell]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name db2-liberty \
           -e AUTOCONFIG=false -e ARCHIVE_LOGS=false -e LICENSE=accept \ 
           -e DBNAME=myDB \
           -e DB2INSTANCE=exampleUser \
           -e DB2INST1_PASSWORD=examplePassword \
           -p 50000:50000 \
           --privileged \
           ibmcom/db2:11.5.0.0a
----

=== Microsoft SQL Server

[source,xml]
----
<dataSource id="DefaultDataSource" jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="driver-library"/>
    <properties.microsoft.sqlserver serverName="localhost" portNumber="1433"
                databaseName="myDB"
                user="SA"
                password="examplePassw0rd"/>

</dataSource>
----

To run a SQL Server Docker container locally:

[source,shell]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name mssql-liberty \
           -e ACCEPT_EULA=Y \
           -e SA_PASSWORD=examplePass0ord \
           -p 1433:1433 \
           mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
----

=== MySQL

[source,xml]
----
<dataSource id="DefaultDataSource" jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="driver-library"/>
    <properties serverName="localhost" portNumber="3306"
                databaseName="myDb"
                user="exampleUser"
                password="examplePassword"/>
</dataSource>
----

To run a MySQL Docker container locally:

[source,shell]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name mysql-liberty \
           -e MYSQL_DATABASE=myDB \
           -e MYSQL_USER=exampleUser \
           -e MYSQL_PASSWORD=examplePassword \
           -p 3306:3306 \
           mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
----

=== Oracle

[source,xml]
----
<dataSource id="DefaultDataSource" jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="driver-library"/>
    <properties.oracle URL="jdbc:oracle:thin:@//localhost:1521/myDB"/>
</dataSource>
----

== Included OSS Components

[options="header",cols="1,1"]
|===
| Liberty Feature | OSS Component
//-------------
| `beanValidation-2.0` | Apache BVal 1.1
| `cdi-1.2` | Weld 2.4.X
| `cdi-2.0` | Weld 3.X
| `javaMail-1.5` | Sun ref impl
| `javaMail-1.6` | Sun ref impl
| `jaxb-2.2` | Sun ref impl
| `jaxb-2.3` | Sun ref impl
| `jaxrs-2.0` | Apache CXF 2.6
| `jaxrs-2.2` | Apache CXF 3.2
| `jaxws-2.2` | Apache CXF 2.6
| `jaxws-2.3` | Apache CXF 3.2
| `jpa-2.1` | EclipseLink 2.6 
| `jpa-2.2` | EclipseLink 2.7
| `jsf-2.2` | Apache MyFaces 2.2
| `jsf-2.3` | Apache MyFaces 2.3
| `jsonb-1.0` | Eclipse Yasson 1.0
| `jsonp-1.0` | Glassfish ref impl
| `jsonp-1.1` | Glassfish ref impl
| `mpReactiveMessaging-1.0` | SmallRye Reactive Messaging
|===

== Replaceable Components

- JPA implementation can be changed (typically to Hibernate) using the `jpaContainer-2.1` or `2.2` features
- JSF implementation can be changed (typically to Mojarra) using the `jsfContainer-2.2` or `2.3` features
- JSON-B implementation can be changed using the `jsonbContainer-1.0` feature
- JSON-P implementation can be changed using the `jsonpContainer-1.0` or `1.1` feature

== Contribute Corrections

Find some incorrect information or want to contribute an additional section?

Fork this document on github and raise a PR: https://github.com/aguibert/openliberty-cheat-sheet[GitHub - openliberty-cheat-sheet]
